### ISSUE TITLE
Unrelated Question

### ISSUE THREAD

**Issue by fancythedeveloper** [kyle95wm/CoWFC#2]
Should the CoWFC installer use this instead of the original by mh9924?

**Comment by kyle95wm** [comment]
Yes, the installer is scripted in such a way that this repository is used instead of the parent repository that it was forked off. While the parent repository may be ahead in commits, it has not merged the changes from this repository. Is the installer not using this repo? Please let me know so I can fix it.

**Comment by fancythedeveloper** [comment]
I don't know about your question, I haven't used the CoWFC installer yet, especially since I need to use Ubuntu (Server) for it. But, if it doesn't then change it.

**Comment by kyle95wm** [comment]
In that case, it does use my repository for the files. The other repository is in the script, but commented out, so it’ll be ignored.
