### ISSUE TITLE
Getting error 23404

### ISSUE THREAD

**Issue by lpearl** [kyle95wm/CoWFC#5]
Hi,

I'm running a lan server on 14.04 and I can't seem to get it working. Running it on a clean 14.04 vm with network bridge, I get error 23404. I have tried changing the nas_server.py ip address to 0.0.0.0:80 but then I get error 20100. Not really sure what to do now.

Hope you can help!

**Comment by kyle95wm** [comment]
Error code 23404 is HTTP return error 404 - not found

Changing the NAS server to use port 80 is NOT recommended and should be handled through a reverse proxy which is run by your web server (apache)

I haven't touched the installer code in such a long time, so I'll test a 14.04 build and see where that puts things. IIRC 16.04 should build just fine. 18.04 has not been tested yet and may never be supported since I have since abandoned primary development on the project.

**Comment by kyle95wm** [comment]
Just built a fresh 14.04 install. I wasn't getting any 404 return errors. Please try 16.04, as 14.04 is considered EOL.

**Comment by lpearl** [comment]
Thanks for the quick response. So I installed a fresh 16.04.5 and is now having a different problem my wii can't connect to the internet (error 52130). I went back into 14.04 to check if it was still working and my wii connected no problem but still error 23404. In 16.04.5 I can connect to the information page. I'm assuming it should work on a vm but I'm going to try and boot ubuntu of usb to see if that makes a difference. Anything I can do on the vm to get it working?

**Comment by kyle95wm** [comment]
Yeah it should work on a VM. Make sure your VM’s connection isn’t NAT’d but bridged so that it’s on the same subnet as your other devices.

**Comment by lpearl** [comment]
Ya, I have checked the setting and its in bridged.

**Comment by lpearl** [comment]
So I ran the code booted without a VM and the same problem with 16.04 where I can't even connect to the internet with the Wii. Is there anything I can do to get it working?

**Comment by kyle95wm** [comment]
Are you using the internal or external address on your Wii? What address did you enter during setup of dnsmasq?

This matters. If you're using the internal address in both locations, it shouldn't be a problem. Using your external address requires you to pot forward, and is basically useless on a LAN since you'll be going out and coming back in and it'll just be a mess.

On another device, try setting it to use your DWC's DNS, and go to pages like:

* conntest.nintendowifi.net
* gamestats.gs.nintendowifi.net
* gamestats2.gs.nintendowifi.net

They should all return some sort of data.

**Comment by lpearl** [comment]
Ok, so I have finally got it to connect on the Wii using 16.04 server version. I'm still getting the 23404 error. I'm assuming you need wiimmfi for this to work right? I have also checked the pages and I'm getting data from them. Any ideas on how to fix the error?

**Comment by kyle95wm** [comment]
53404 is unknown according to Wiimmfi. Did you mis-type the error code? Does the connection test succeed?

**Comment by lpearl** [comment]
Sorry made an edit don't know if it appeared. But I meant 23404 and yes the Wii is finally succeeding the connection test on 16.04. I just have no idea how to fix the error.

**Comment by kyle95wm** [comment]
Hm, I'm not sure what to really say. Are you using a patched game (no SSL patch)?

While I haven't tested connecting from an actual game, all other tests suggest that the server should be able to accept connections to the needed domains.

**Comment by lpearl** [comment]
I got it working!!!! I ended up trying to connect to a server posted on the wiki and it didn't work. So I tried removing the wiimmfi patch. It connected to both the online server and my LAN server (after adding the game to the whitelist and delete my save game). I have no idea why I thought I needed the patcher. Can't wait to have a tournament with my friends and thanks so much for all your help!!!!

**Comment by kyle95wm** [comment]
np!
